//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVC_Employee
    {
        public int E_Id { get; set; }
        public string E_FirstName { get; set; }
        public string E_LastName { get; set; }
        public string E_mail { get; set; }
        public string E_Contact { get; set; }
    }
}
